server:
  port: 8082

spring:
  application:
    name: attendee-management
  datasource:
    url: jdbc:mysql://localhost:3306/attendee_management
    username: root
    password: W1l#T1d#O1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
